apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: ethio-dev-worker
  title: serverless function
  description: Create a route and attach a function on that route under a specified api gateway. This potentially generates a repo with serverless code
  tags:
    - worker
    - function
    - serverless
    - api
    - route
spec:
  owner: dev@ethio.dev
  type: resource
  parameters:
    - title: Provide details for your function
      required:
        - function_name
        - route
        - gateway
      properties:
        function_name:
          title: Function Name
          type: string
          description: A name for your serverless function.
        route:
          title: route
          type: string
          description: a route where you can attach this function to eg. subdomain.ethio.dev/route. 
        gateway:
          title: Gateway
          type: string
          description: The api gateway name aka the subdomain where you want to attach this route and function to.
          ui:options:
            allowedKinds:
              - Resource
  steps:
    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        url: https://api.github.com/users/getachew
