apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: ethio-dev-api-gateway
  title: ethio.dev api gateway
  description: creates a subdomain on ethio.dev. You can then create routes and serverless functions and use this subdomain as an api gateway
  tags:
    - gateway
    - subdomain
    - api
    - serverless
    - function
spec:
  owner: dev@ethio.dev
  type: resource
  parameters:
    - title: Provide some information on this subdomain requirements
      required:
        - subdomain
        - owner
      properties:
        subdomain:
          title: Name
          type: string
          description: Unique name for the subdomain
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
  steps:
    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        url: https://api.github.com/users/getachew
