apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: ethio-dev-api-gateway
  title: API Gateway
  description: Create subdomain on ethio.dev. This subdomain is your api gateway to attach your serverless functions and routes
  tags:
    - gateway
    - subdomain
    - api
spec:
  owner: dev@ethio.dev
  type: resource
  parameters:
    - title: Configure your API Gateway
      required:
        - subdomain
        - owner
      properties:
        subdomain:
          title: Name
          type: string
          description: Unique name for the subdomain
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
  steps:
    - id: create-subdomain
      name: Create Subdomain
      action: ethiodev:create-subdomain
      input:
        subdomain: '{{ parameters.subdomain }}'
        owner: '{{ parameters.owner }}'
